// <auto-generated />
using System;
using ApiRestaurantPro.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRestaurantPro.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251030180546_CreateNewDB")]
    partial class CreateNewDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRestaurantPro.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Address = "Head Office - Sohag",
                            ConcurrencyStamp = "78c5bd1d-5648-4c72-9da3-0ebdd0cc75d2",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "admin@restaurant.com",
                            EmailConfirmed = true,
                            ImageUrl = "/images/users/admin.jpg",
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@RESTAURANT.COM",
                            NormalizedUserName = "ADMIN@RESTAURANT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDEgzaXD0X+n03zYh/xTi2NTHBsU4YsS6FRYvIKRhxE9mlpgdT5MkDY1rfPOhoxm7g==",
                            PhoneNumber = "01000000000",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9dbb0cde-0411-404f-8f8e-ffae57e810b1",
                            TwoFactorEnabled = false,
                            UserName = "admin@restaurant.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "2d85ac18-c822-433c-9321-ca25a87cabbb",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "visitor@restaurant.com",
                            EmailConfirmed = true,
                            ImageUrl = "/images/users/visitor.jpg",
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VISITOR@RESTAURANT.COM",
                            NormalizedUserName = "VISITOR@RESTAURANT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL7FXYl+3nVTHB1LtN4z5+sa695nQvtN+uLgGmGxTd+V98laRKR8U7SsJeOl3nCOpQ==",
                            PhoneNumber = "01011111111",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5459fa2c-bddc-4f92-8dea-6fbb02dc0b26",
                            TwoFactorEnabled = false,
                            UserName = "visitor@restaurant.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            Address = "Sohag, Egypt",
                            ConcurrencyStamp = "e1c698f2-5c59-4d6d-889e-5aa600ca52a0",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "subscriber@restaurant.com",
                            EmailConfirmed = true,
                            ImageUrl = "/images/users/subscriber.jpg",
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUBSCRIBER@RESTAURANT.COM",
                            NormalizedUserName = "SUBSCRIBER@RESTAURANT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJlcbwV42ADBheVX+Wawu9FHDX+ZvSY/j+Yhxuor65OPb7wFyRBni1UwsjqhsskzUQ==",
                            PhoneNumber = "01022222222",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a977dfd3-83a4-49eb-a83f-54b68d648476",
                            TwoFactorEnabled = false,
                            UserName = "subscriber@restaurant.com"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            Address = "Alexandria, Egypt",
                            ConcurrencyStamp = "7700d0b4-6668-4240-8d40-18a74e6bb238",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "customer@restaurant.com",
                            EmailConfirmed = true,
                            ImageUrl = "/images/users/customer.jpg",
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@RESTAURANT.COM",
                            NormalizedUserName = "CUSTOMER@RESTAURANT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOQlxQA5cOGDsaC36sAQtf2rpttgYSRlJ1YYBI6QEIW+R8nbxPCP5ODzJ31GgZzdfw==",
                            PhoneNumber = "01033333333",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e37977c-5c10-4651-b0df-a01a6def6143",
                            TwoFactorEnabled = false,
                            UserName = "customer@restaurant.com"
                        });
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Start your meal with our delicious appetizers and salads",
                            ImageUrl = "/images/categories/catFood.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Our signature main dishes prepared fresh daily",
                            ImageUrl = "/images/categories/catFood.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Main Courses"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Hot and cold drinks to complement your meal",
                            ImageUrl = "/images/categories/userImage.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Sweet treats to end your meal perfectly",
                            ImageUrl = "/images/categories/userImage.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DailyOrderCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Traditional Greek salad with feta cheese, olives, and fresh vegetables",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Greek Salad",
                            PreparationTime = 10,
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Creamy tomato soup served hot with garlic bread",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Tomato Soup",
                            PreparationTime = 15,
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Classic Caesar salad with crispy croutons and parmesan",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Caesar Salad",
                            PreparationTime = 10,
                            Price = 22.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Premium grilled beef steak with seasonal vegetables",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Beef Steak",
                            PreparationTime = 30,
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Marinated grilled chicken breast served with rice",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Grilled Chicken",
                            PreparationTime = 25,
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Fresh Atlantic salmon with lemon butter sauce",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Salmon Fillet",
                            PreparationTime = 20,
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Creamy pasta with bacon and parmesan cheese",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Pasta Carbonara",
                            PreparationTime = 18,
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "100% natural fresh orange juice",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Fresh Orange Juice",
                            PreparationTime = 5,
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Traditional Turkish coffee",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Turkish Coffee",
                            PreparationTime = 8,
                            Price = 8.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Cold espresso with milk and ice",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Iced Latte",
                            PreparationTime = 5,
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Classic New York cheesecake with strawberry topping",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Cheesecake",
                            PreparationTime = 10,
                            Price = 28.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Warm chocolate cake with molten center",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chocolate Lava Cake",
                            PreparationTime = 15,
                            Price = 32.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DailyOrderCount = 0,
                            Description = "Italian classic with coffee-soaked ladyfingers",
                            ImageUrl = "/images/menu/MenuItem.jpeg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Tiramisu",
                            PreparationTime = 10,
                            Price = 30.00m
                        });
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("EstimatedDeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            CustomerName = "Subscriber User",
                            DeliveryAddress = "Sohag, Egypt",
                            Discount = 0.00m,
                            IsDeleted = false,
                            OrderType = 1,
                            PaymentMethod = 1,
                            PhoneNumber = "01022222222",
                            Status = 1,
                            Subtotal = 150.00m,
                            Tax = 0.00m,
                            Total = 150.00m,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            CustomerName = "Subscriber User",
                            DeliveryAddress = "Sohag, Egypt",
                            Discount = 0.00m,
                            IsDeleted = false,
                            OrderType = 1,
                            PaymentMethod = 2,
                            PhoneNumber = "01022222222",
                            Status = 4,
                            Subtotal = 85.00m,
                            Tax = 0.00m,
                            Total = 85.00m,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 14, 22, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            CustomerName = "Subscriber User",
                            DeliveryAddress = "Sohag, Egypt",
                            Discount = 0.00m,
                            IsDeleted = false,
                            OrderType = 1,
                            PaymentMethod = 1,
                            PhoneNumber = "01022222222",
                            Status = 2,
                            Subtotal = 202.00m,
                            Tax = 0.00m,
                            Total = 202.00m,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            CustomerName = "Customer User",
                            DeliveryAddress = "Alexandria, Egypt",
                            Discount = 0.00m,
                            IsDeleted = false,
                            OrderType = 1,
                            PaymentMethod = 1,
                            PhoneNumber = "01033333333",
                            Status = 5,
                            Subtotal = 110.00m,
                            Tax = 0.00m,
                            Total = 110.00m,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 14, 23, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            CustomerName = "Customer User",
                            DeliveryAddress = "Alexandria, Egypt",
                            Discount = 0.00m,
                            IsDeleted = false,
                            OrderType = 1,
                            PaymentMethod = 2,
                            PhoneNumber = "01033333333",
                            Status = 3,
                            Subtotal = 170.00m,
                            Tax = 0.00m,
                            Total = 170.00m,
                            UserId = "4"
                        });
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            IsDeleted = false,
                            MenuItemId = 4,
                            OrderId = 1,
                            Price = 0m,
                            Quantity = 1,
                            Subtotal = 85.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            IsDeleted = false,
                            MenuItemId = 1,
                            OrderId = 1,
                            Price = 0m,
                            Quantity = 2,
                            Subtotal = 50.00m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            IsDeleted = false,
                            MenuItemId = 10,
                            OrderId = 1,
                            Price = 0m,
                            Quantity = 1,
                            Subtotal = 15.00m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            IsDeleted = false,
                            MenuItemId = 4,
                            OrderId = 2,
                            Price = 0m,
                            Quantity = 1,
                            Subtotal = 85.00m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 14, 22, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            IsDeleted = false,
                            MenuItemId = 6,
                            OrderId = 3,
                            Price = 0m,
                            Quantity = 2,
                            Subtotal = 150.00m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 14, 22, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            IsDeleted = false,
                            MenuItemId = 11,
                            OrderId = 3,
                            Price = 0m,
                            Quantity = 1,
                            Subtotal = 28.00m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 14, 22, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            IsDeleted = false,
                            MenuItemId = 8,
                            OrderId = 3,
                            Price = 0m,
                            Quantity = 2,
                            Subtotal = 24.00m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            IsDeleted = false,
                            MenuItemId = 5,
                            OrderId = 4,
                            Price = 0m,
                            Quantity = 2,
                            Subtotal = 110.00m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 14, 23, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Customer",
                            IsDeleted = false,
                            MenuItemId = 4,
                            OrderId = 5,
                            Price = 0m,
                            Quantity = 2,
                            Subtotal = 170.00m
                        });
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalEstimatedPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DesiredQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d5ea1f20-90eb-4410-ba24-bc6dcbfe435f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "9b8820f0-06db-453e-b239-fb957b1bced8",
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        },
                        new
                        {
                            Id = "389a19b5-c8d6-4ca5-975e-5a91880aa60a",
                            Name = "Subscriber",
                            NormalizedName = "SUBSCRIBER"
                        },
                        new
                        {
                            Id = "a0f09c4e-9f85-478b-afd4-24a16858a18c",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole<string>");

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-visitor",
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        },
                        new
                        {
                            Id = "role-subscriber",
                            Name = "Subscriber",
                            NormalizedName = "SUBSCRIBER"
                        },
                        new
                        {
                            Id = "role-customer",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.Cart", b =>
                {
                    b.HasOne("ApiRestaurantPro.Models.ApplicationUser", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ApiRestaurantPro.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.CartItem", b =>
                {
                    b.HasOne("ApiRestaurantPro.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiRestaurantPro.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.MenuItem", b =>
                {
                    b.HasOne("ApiRestaurantPro.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.Order", b =>
                {
                    b.HasOne("ApiRestaurantPro.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.OrderItem", b =>
                {
                    b.HasOne("ApiRestaurantPro.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiRestaurantPro.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.Wishlist", b =>
                {
                    b.HasOne("ApiRestaurantPro.Models.ApplicationUser", "User")
                        .WithOne("Wishlist")
                        .HasForeignKey("ApiRestaurantPro.Models.Wishlist", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.WishlistItem", b =>
                {
                    b.HasOne("ApiRestaurantPro.Models.MenuItem", "MenuItem")
                        .WithMany("WishlistItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiRestaurantPro.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistItems")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApiRestaurantPro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApiRestaurantPro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiRestaurantPro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApiRestaurantPro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.ApplicationUser", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ApiRestaurantPro.Models.Wishlist", b =>
                {
                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
